server:
  port: 8082
spring:
  application:
    name: user
  profiles:
    active: dev
    
eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
